### ISSUE TITLE
collect2: error:

### ISSUE THREAD

**Issue by sec13b** [EgeBalci/amber#27]
┌──(kali㉿kali)-[~/Desktop/Client]
└─$ go install github.com/EgeBalci/amber@latest
# github.com/EgeBalci/amber
/usr/lib/go-1.21/pkg/tool/linux_amd64/link: running gcc failed: exit status 1
/usr/bin/ld: cannot find -lkeystone: No such file or directory
/usr/bin/ld: cannot find -lkeystone: No such file or directory
collect2: error: ld returned 1 exit status

                                                                                                                                
┌──(kali㉿kali)-[~/Desktop/Client]
how i can solve this.
thank you

**Comment by Z1xus** [comment]
install keystone. https://github.com/keystone-engine/keystone/blob/master/docs/COMPILE.md
