### ISSUE TITLE
Missing handler file

### ISSUE THREAD

**Issue by stevenfonz** [EgeBalci/Amber#4]
Hi, may I know how to i issue handler command like ./handler /test/putty.exe.stage 4444 with this latest branch? 

Can we still download the previous branch which version without docker?

**Comment by EgeBalci** [comment]
Hi, I decided to separate handler script from this project. I plan to release a more capable handler code in a different repo. Until then you can still use the old handler.go file here https://github.com/EgeBalci/Amber/blob/8663119d9cfd818c86ed1a3a1988b5c1aa5e1453/handler.go

Build it with `go build handler.go`
