### ISSUE TITLE
Cannot find file to PE Pack

### ISSUE THREAD

**Issue by motox1** [EgeBalci/Amber#6]
Hello,

I am trying to test this with an application and cannot have amber find the file:

root@test/# docker run -it egee/amber -r /putty.exe

[*] File: /putty.exe
[*] Reflective: true
[*] Key Size: 8
[*] API: EAT
[*] Verbose: false

 5 / 24 [============>----------------------------------------------]  20.83% 0s

2019/06/01 20:14:22 open /putty.exe: no such file or directory
root@test/#

**Comment by EgeBalci** [comment]
If you are using the docker version you need to mount the working directory to the container with `-v` parameter. If you check the ***Docker Usage*** example you can see `docker run -it -v /tmp/:/tmp/ amber /tmp/file.exe` it mounts the directory `/tmp/` wich contains the `file.exe`

**Comment by motox1** [comment]
thank you for the info. I am not able to get staged putty.exe.stage to open with meterpreter/reverse_tcp stager. It will send the stage but does not run the exe in memory on the endpoint.please let me know your thoughts.Thank you,Cliff


-------- Original Message --------
Subject: Re: [EgeBalci/Amber] Cannot find file to PE Pack (#6)

**Comment by EgeBalci** [comment]
I couldn't understand what you are trying to do please explain with more detail.

**Comment by motox1** [comment]
Like in your video on the blog. you are able to take a metasploit payload had have it connect via reverse_tcp then execute the putty application over the handler. Mine will send from handler but I never see it in process explorer on the endpoint.Can you help me? Does the handler work with other payload types like reverse DNS or Revers https?Thank you

-------- Original Message --------
Subject: Re: [EgeBalci/Amber] Cannot find file to PE Pack (#6)

**Comment by EgeBalci** [comment]
Be careful with the architectures, if you trying to run 64 bit putty you also need to use a 64 bit meterpreter reverse TCP payload :)   Handler currently only supports reverse TCP payloads but soon i'll improve it by adding support for HTTP,HTTPS etc...

**Comment by motox1** [comment]
Do you have a timeframe for the handler to support TCP x64 reverse payload windows?I would like to use the handler but every payload I make in 32 bit tcp reverse the DLP detects this and I cannot execute the payload to call the handler. With x64 payload it bypasses DLP but I cannot user handler to execute the exe  (Putty) in memory.Please let me know your thoughts.Thank you


-------- Original Message --------
Subject: Re: [EgeBalci/Amber] Cannot find file to PE Pack (#6)
